#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export TERM=xterm-256color

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# FZF
#
export FZF_DEFAULT_COMMAND='ag -l 2> /dev/null'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_OPTS='--color light'

# because typing 'cd' is A LOT of work!!
alias ..='cd ../'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'

# Emacs client
alias e='emacsclient -c'
# Neovim
alias vim='nvim'

# tmux
alias tk='tmux kill-session'
alias ts='tmuxinator start'

# ssh
alias ssh='ssh -Y'

stty -ixon
[ -n "$TMUX" ] && export TERM=screen-256color
# dircolors
eval `dircolors ~/.dotfiles/dircolors-solarized/dircolors.256dark`

# key-binding
fancy-ctrl-z () {
  if [[ $#BUFFER -eq 0 ]]; then
    fg
    zle redisplay
  else
    zle push-input
    zle clear-screen
  fi
}
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

source "/etc/zsh_command_not_found"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/.dotfiles/vim/gruvbox_256palette.sh ] && source ~/.dotfiles/vim/gruvbox_256palette.sh
