#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export TERM=xterm-256color

#
# Editors
#

export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'

#
# FZF
#
export FZF_DEFAULT_COMMAND='(git ls-tree -r --name-only HEAD || ag -l --nocolor -g "") 2> /dev/null'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_OPTS='--color light'

#
# Mac os location based proxy auto config
#
if [[ $OSTYPE =~ 'darwin' ]]; then
  proxy_string=`networksetup -getwebproxy 'Wi-Fi'`
  proxy_enabled=`print $proxy_string | head -n 1 | awk '{print $2}'`
  if [[ $proxy_enabled == 'Yes' ]]; then
    export http_proxy=`print $proxy_string | awk '{ print $2}' | awk '{getline l2; getline l3; print "http://"l2":"l3}' | head -n 1`
    export https_proxy=$http_proxy
    export ALL_PROXY=$http_proxy
  else
    unset http_proxy
    unset https_proxy
    unset ALL_PROXY
  fi
fi

# because typing 'cd' is A LOT of work!!
alias ..='cd ../'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'

# Emacs client
alias e='emacsclient -c'
# Neovim
alias vim='nvim'

# tmux
alias tk='tmux kill-session'
alias ts='tmuxinator start'

# ssh
alias ssh='ssh -Y'

stty -ixon
[ -n "$TMUX" ] && export TERM=tmux-256color

# key-binding
fancy-ctrl-z () {
  if [[ $#BUFFER -eq 0 ]]; then
    fg
    zle redisplay
  else
    zle push-input
    zle clear-screen
  fi
}
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

if [[ $OSTYPE =~ 'linux' ]]; then
  #statements
  source "/etc/zsh_command_not_found"
  # dircolors
  eval `dircolors ~/.dotfiles/dircolors-solarized/dircolors.256dark`
fi
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/.gruvbox_256palette.sh ] && source ~/.gruvbox_256palette.sh
